name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: echo "Deploy to DEV environment"

  qa:
    runs-on: ubuntu-latest
    needs: dev   # espera que 'dev' termine
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: echo "Deploy to QA environment"

  prod:
    runs-on: ubuntu-latest
    needs: qa   # espera que 'qa' termine
    if: github.ref == 'refs/heads/main'  # solo deploya en main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: echo "Deploy to PROD environment"
